Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2021-11, with the labels that each got.

#12 Fix data plane image builds
  openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/broker-receiver/Dockerfile
Labels: approved, lgtm

#14 [release-v0.26] Separate step for just launching Kafka cluster (Strimzi)
  hack/run.sh
  test/e2e-common.sh
Labels: approved, lgtm

#15 Adding install base for running CI... part I
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#16 Tweak config for OCP, similar was done to DP already
  control-plane/config/100-config-logging.yaml
  control-plane/config/100-config-tracing.yaml
  control-plane/config/500-controller.yaml
  control-plane/config/sink/500-webhook.yaml
Labels: approved, lgtm

#17 [release-v0.26] Adding release build scripts and install broker
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
  openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
  openshift/release/mirror-upstream-branches.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#19 Add missing cm
  control-plane/config/100-config-logging.yaml
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
Labels: approved, lgtm

#18 Override image template and run e2e tests
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  test/e2e/broker_trigger_sink_test.go
  test/e2e/kafka_sink_test.go
  test/e2e/sacura_test.go
Labels: approved, lgtm

#21 [release-v0.26] Cherry pick 1450
  control-plane/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedOffsetManagerBenchmark.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  test/config/chaos/chaosduck.yaml
  test/e2e-common.sh
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, lgtm

#20 [release-v0.26] Comment out sink ctrl
  control-plane/cmd/kafka-controller/main.go
Labels: approved, lgtm

#22 E2E_new test suite execution
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
Labels: approved, lgtm

#13 Patch min. version for OCP 4.6
  vendor/knative.dev/pkg/version/version.go
Labels: approved, do-not-merge/hold

#24 Add openshift stash 1.0
  .github/workflows/OWNERS
  .github/workflows/build-dependabot-pr.yaml
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-java-test.yaml
  .github/workflows/knative-profile-data-plane.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  .github/workflows/knative-vulnerability.yaml
  .github/workflows/update-dependabot-pr.yaml
  Makefile
  OWNERS
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/build-image/kubernetes.repo
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/broker-dispatcher/generate_jdk.sh
  openshift/ci-operator/knative-images/broker-receiver/Dockerfile
  openshift/ci-operator/knative-images/broker-receiver/generate_jdk.sh
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-flaker/Dockerfile
  openshift/ci-operator/knative-test-images/event-library/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/partitions-replication-verifier/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/source-image/Dockerfile
  openshift/ci-operator/update-ci.sh
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/mirror-upstream-branches.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#25 CI was here...:fire:
  ci
Labels: approved

#26 Adding some stuff for midstream manifests generation
  control-plane/config/200-controller/100-config-tracing.yaml
  control-plane/config/200-controller/500-controller.yaml
  control-plane/config/200-webhook/500-webhook.yaml
  data-plane/config/broker/template/500-dispatcher.yaml
  data-plane/config/broker/template/500-receiver.yaml
  data-plane/config/sink/template/500-receiver.yaml
  hack/data-plane.sh
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
  openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
Labels: approved, lgtm

#27 Not always appending to manifests
  openshift/release/generate-release.sh
Labels: approved, lgtm

#28 Adding 755 mod
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved

#31 [release-v1.0] Reorder scripts
  openshift/e2e-tests.sh
  test/kafka/kafka_setup.sh
Labels: approved, lgtm, do-not-merge/hold

#30 [release-v0.26] Remove the GA from upstream
  .github/workflows/OWNERS
  .github/workflows/build-dependabot-pr.yaml
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-java-test.yaml
  .github/workflows/knative-profile-data-plane.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  .github/workflows/knative-vulnerability.yaml
  .github/workflows/update-dependabot-pr.yaml
Labels: approved, lgtm

#34 More test tweaks
  test/e2e/broker_trigger_sink_test.go
  test/e2e/kafka_sink_test.go
  test/e2e/sacura_test.go
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
Labels: approved, lgtm

#32 [release-v0.26] BACKPORT: Commit offset on consumer close
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
Labels: approved, lgtm

#29 [release-v0.26] Golang 1.17 container image
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#36 [release-v1.0] Golang 1.17 container image
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#38 Remove ansible
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#37 Remove ansible
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#39 [release-v0.26] Properly handle events without the `data` field
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, lgtm

#43 Using UBI 8 with Java-17 image as Runtime
  openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/broker-receiver/Dockerfile
Labels: approved, lgtm

#45 Execute only regular e2e suite
  ci
  openshift/e2e-tests.sh
Labels: approved, lgtm

#46 Using UBI 8 with OpenJDK-17 image as Runtime :penguin: (#43)
  openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/broker-receiver/Dockerfile
Labels: approved, lgtm

#48 [release-v1.0] Using sink receiver
  openshift/e2e-common.sh
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm

#47 [release-v1.0] :detective: some more tests for KafkaSink enabled
  test/e2e/broker_trigger_sink_test.go
  test/e2e/kafka_sink_test.go
Labels: approved, lgtm

#49 [release-v1.0] Adding conformance tests
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#51 Remove myself from OWNERS
  OWNERS
Labels: approved, lgtm

#52 [RELEASE-v1.0] Remove myself from OWNERS
  OWNERS
Labels: approved, lgtm

#53 [RELEASE-v0.26] Remove myself from OWNERS
  OWNERS
Labels: approved, lgtm
