Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2022-03, with the labels that each got.

#137 Regenerate yamls
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
Labels: approved, lgtm

#139 Update manifests
  control-plane/config/eventing-kafka-broker/200-controller/100-config-tracing.yaml
  control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
  control-plane/config/eventing-kafka-broker/200-webhook/500-webhook.yaml
  data-plane/config/broker/500-dispatcher.yaml
  data-plane/config/broker/500-receiver.yaml
  data-plane/config/sink/500-receiver.yaml
  data-plane/config/source/500-dispatcher.yaml
  hack/update-checksums.sh
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
  openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
Labels: approved, lgtm

#142 [release-v1.1] Use broker status annotations to stamp ConfigMap reference
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
Labels: approved, lgtm

#143 [release-v1.1] Get external topics
  control-plane/pkg/reconciler/broker/broker.go
Labels: approved, lgtm

#144 [release-v1.1] Backport of upstream 1987
  control-plane/pkg/reconciler/broker/broker.go
Labels: approved, lgtm

#150 [release-v1.0] Skip GPG check for kubernetes repository
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm

#149 [release-v1.1] Skip GPG check for kubernetes repository
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm

#148 [release-v0.26] Skip GPG check for kubernetes repository
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm

#147 :robot: CI was here...:fire:
  ci
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, do-not-merge/hold

#153 [release-v1.2] Fix recent import change
  test/test_images/kafka-consumer/consumer.go
Labels: approved, lgtm

#154 [release-v1.1] Poll for new records when `max.poll.records` limit isn't reached (#2003)
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticleTest.java
Labels: approved, lgtm

#155 [release-v1.1] KafkaSource lease remapping
  control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-leader-election.yaml
  hack/control-plane.sh
  openshift/patches/support-map-lease-prefix-in-pkg.patch
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
  test/e2e-common.sh
  test/e2e_new/features/leases.go
  test/e2e_new/lease_test.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
Labels: approved, lgtm

#158 [release-v1.2] KafkaSource lease remapping (#155)
  control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-leader-election.yaml
  hack/control-plane.sh
  openshift/patches/support-map-lease-prefix-in-pkg.patch
  openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
  test/e2e-common.sh
  test/e2e_new/features/leases.go
  test/e2e_new/lease_test.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
Labels: approved, lgtm

#100 Update community files (#1868)
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#161 [v1.2] Improve dispatcher components stop lifecycle
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseToKafkaTopicHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Labels: approved, lgtm

#164 Remove devguyio from OWNERS_ALIASES
  OWNERS
Labels: approved, lgtm
