Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2022-12, with the labels that each got.

#491 Update eventing nightly (#2813)
  ci
Labels: kind/sync-fork-to-upstream

#492 [release-v1.6] Handle ConsumerGroup finalization for deleted topics
  control-plane/pkg/kafka/testing/admin_mock.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/testing/errors.go
Labels: approved

#494 [release 1.6] Missing unit tests for namespaced broker (#2817)
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/namespaced_broker_test.go
  control-plane/pkg/reconciler/testing/listers.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/testing/objects_consumergroup.go
  vendor/github.com/manifestival/manifestival/fake/client.go
  vendor/modules.txt
Labels: approved, lgtm

#495 [release-v1.6] Source v2 pod version selector for upgrade
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  data-plane/config/source/500-dispatcher.yaml
  go.mod
  openshift/release/artifacts/eventing-kafka-source.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved

#500 [main] Add patch to skip namespaced broker propagation test
  openshift/patches/skip_namespaced_broker_propagation_test.patch
Labels: approved, lgtm

#499 [release-v1.6] Propagate additional resources in Broker namespaced reconciler
  control-plane/config/eventing-kafka-broker/200-controller/100-config-namespaced-broker-resources.yaml
  control-plane/pkg/propagator/resource_propagator.go
  control-plane/pkg/propagator/resource_propagator_test.go
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/base/reconciler_test.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/namespaced_broker.go
  control-plane/pkg/reconciler/broker/namespaced_broker_test.go
  control-plane/pkg/reconciler/broker/namespaced_controller.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/channel/v2/channelv2_test.go
  control-plane/pkg/reconciler/channel/v2/controllerv2.go
  control-plane/pkg/reconciler/consumer/consumer.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/namespaced_controller.go
  control-plane/pkg/reconciler/trigger/namespaced_trigger.go
  go.mod
  openshift/patches/skip_namespaced_broker_propagation_test.patch
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka.yaml
  test/e2e_new/broker_test.go
  test/e2e_new/features/featuressteps/broker.go
  test/e2e_new/features/namespaced_broker.go
  test/e2e_new/resources/configmap/wait.go
Labels: approved, lgtm

#504 [release-v1.4] Patching the pom for latest of Jackson (2.14.1)
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#506 [release-v1.6] Patching the pom for latest of Jackson (2.14.1)
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#512 [release-v1.7] Restrict wildcard rbac apiGroups (#2844)
  control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml
  control-plane/config/post-install/200-controller-cluster-role.yaml
  data-plane/config/broker/200-broker-data-plane-cluster-role.yaml
  data-plane/config/channel/200-channel-data-plane-cluster-role.yaml
  data-plane/config/sink/200-sink-data-plane-cluster-role.yaml
  data-plane/config/source/200-source-data-plane-cluster-role.yaml
Labels: approved, lgtm

#511 [release-v1.7] Run make release 1.7
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
  openshift/release/artifacts/eventing-kafka.yaml
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/eventing/test/test_images/print/pod.yaml
  vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: approved, lgtm

#517 [release-v1.7] Do not block finalization if secret for external topic is gone
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
Labels: approved, lgtm

#521 [release-v1.6] Using matching branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#522 [1.6] Templating support in namespaced broker additional resources
  control-plane/pkg/propagator/resource_propagator.go
  control-plane/pkg/propagator/resource_propagator_test.go
  control-plane/pkg/reconciler/broker/namespaced_broker.go
  go.mod
  test/e2e_new/features/featuressteps/broker.go
  test/e2e_new/features/namespaced_broker.go
Labels: approved, lgtm
