Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2022-05, with the labels that each got.

#231 [release-v1.2] Execute new e2e test suite on OCP
  Makefile
  openshift/e2e-common.sh
Labels: approved, lgtm

#235 [release-v1.2] Going with debug to reduce verbosity for retention duration default usage
  control-plane/pkg/reconciler/channel/channel.go
Labels: approved, lgtm

#237 [release-v1.2] Adding disable fips for our midstream
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
Labels: approved, lgtm

#240 [release-v1.2] Wait 10 mins before deleting the consolidated channel dataplane (#2133)
  control-plane/cmd/post-install/kafka_channel_post_migration_deleter.go
Labels: approved, lgtm, do-not-merge/hold

#236 [release-v1.3] Prefactor new e2e 1.3
  openshift/e2e-common.sh
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/eventing/test/test_images/print/pod.yaml
  vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: approved, lgtm

#241 [release-v1.2] Backport of 2139
  control-plane/pkg/security/secret.go
  control-plane/pkg/security/secret_test.go
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuthTest.java
Labels: approved, lgtm

#247 Update patches for rekt images 1.2
  openshift/patches/override-rekt-images.patch
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/eventing/test/test_images/print/pod.yaml
  vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml
Labels: approved, lgtm

#248 [release-v1.2] Build eventshub
  Makefile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/e2e-common.sh
Labels: approved, lgtm

#246 [release-v1.2] Manual dep bump 20220509
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/channel/consolidated/reconciler/controller/resources/service.go
  vendor/knative.dev/eventing-kafka/test/upgrade/continual/channel.go
  vendor/modules.txt
Labels: approved, lgtm

#251 [release-v1.3] Build eventshub
  Makefile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/e2e-common.sh
Labels: approved, lgtm

#249 Update eventhubs patch 1.2
  openshift/patches/override-rekt-images.patch
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: approved, lgtm

#252 [release-v1.3] Adding correct coordinates for the versioned REKT TEST images
  openshift/patches/override-rekt-images.patch
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/eventing/test/test_images/print/pod.yaml
  vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml
  vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: approved, lgtm

#233 [release-v1.3] Adding new target for rekt tests
  Makefile
  openshift/e2e-common.sh
  openshift/e2e-rekt-tests.sh
Labels: approved, lgtm

#255 [release-v1.2] #Backport: Adding 408 to retry list
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Labels: approved, lgtm

#250 [v1.2] Prober targets service instead of pods directly (#2112)
  control-plane/pkg/prober/async_prober.go
  control-plane/pkg/prober/async_prober_test.go
  control-plane/pkg/prober/prober.go
  control-plane/pkg/prober/prober_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/sink/controller.go
  data-plane/config/broker/500-receiver.yaml
  data-plane/config/channel/500-receiver.yaml
  data-plane/config/sink/500-receiver.yaml
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
Labels: approved, lgtm

#254 [release-v1.3] Manual dep bump for ocp
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/channel/consolidated/reconciler/controller/resources/service.go
  vendor/knative.dev/eventing-kafka/test/upgrade/continual/channel.go
  vendor/modules.txt
Labels: approved, lgtm

#253 [release-v1.2] Clean up ordered delivery verticle (#2145)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutor.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutorTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java
Labels: approved, lgtm

#258 [1.2] Port from upstream: Use host-based routing in KafkaChannel
  control-plane/pkg/prober/async_prober.go
  control-plane/pkg/prober/async_prober_test.go
  control-plane/pkg/prober/prober.go
  control-plane/pkg/prober/prober_test.go
  control-plane/pkg/receiver/routing.go
  control-plane/pkg/receiver/routing_test.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/testing/objects_channel.go
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
Labels: approved, lgtm

#260 [release-v1.1] Move up the check if topic is externally managed
  control-plane/pkg/reconciler/broker/broker.go
Labels: approved, lgtm

#263 [v1.2] KafkaChannel migrator adds the secret ref only when previously specificied
  control-plane/cmd/post-install/kafka_channel_migrator.go
Labels: approved, lgtm

#262 [release-v1.2] Remove KafkaSource migration logic
  control-plane/cmd/post-install/kafka_source_deleter.go
  control-plane/cmd/post-install/kafka_source_migrator.go
  control-plane/cmd/post-install/main.go
  control-plane/cmd/post-install/so_kafka_source_deleter.go
Labels: approved, lgtm

#264 [release-v1.2 ]Disable unnecessary metrics (#2156)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
Labels: approved, lgtm

#269 [release-v1.2] Crash on out of memory error apply ocp
  data-plane/config/broker/500-dispatcher.yaml
  data-plane/config/broker/500-receiver.yaml
  data-plane/config/brokerv2/500-dispatcher.yaml
  data-plane/config/channel/500-dispatcher.yaml
  data-plane/config/channel/500-receiver.yaml
  data-plane/config/channelv2/500-dispatcher.yaml
  data-plane/config/sink/500-receiver.yaml
  data-plane/config/source/500-dispatcher.yaml
  data-plane/config/sourcev2/500-dispatcher.yaml
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
Labels: approved, lgtm

#271 [release-v1.3] backport manifest changes
  data-plane/config/broker/500-dispatcher.yaml
  data-plane/config/broker/500-receiver.yaml
  data-plane/config/brokerv2/500-dispatcher.yaml
  data-plane/config/channel/500-dispatcher.yaml
  data-plane/config/channel/500-receiver.yaml
  data-plane/config/channelv2/500-dispatcher.yaml
  data-plane/config/sink/500-receiver.yaml
  data-plane/config/source/500-dispatcher.yaml
  data-plane/config/sourcev2/500-dispatcher.yaml
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
Labels: approved, lgtm

#270 Fips patch ocp
  data-plane/config/broker/500-dispatcher.yaml
  data-plane/config/broker/500-receiver.yaml
  data-plane/config/brokerv2/500-dispatcher.yaml
  data-plane/config/channel/500-dispatcher.yaml
  data-plane/config/channel/500-receiver.yaml
  data-plane/config/channelv2/500-dispatcher.yaml
  data-plane/config/sink/500-receiver.yaml
  data-plane/config/source/500-dispatcher.yaml
  data-plane/config/sourcev2/500-dispatcher.yaml
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
Labels: approved, lgtm

#272 [release-v1.2] Remove old Config Kafka CM for old/legacy channel
  control-plane/cmd/post-install/kafka_channel_post_migration_deleter.go
Labels: approved, lgtm

#268 [release v1.2] Handle committing offsets on revoked partitions
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
Labels: approved

#277 [release-v1.2] Use openshift knative kafkacat
  openshift/patches/use_kafkacat_from_ocp.patch
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
Labels: approved

#266 External topic annotation 1.2
  control-plane/pkg/reconciler/broker/broker.go
Labels: approved

#279 [release-v1.2] Fix RBAC for deletion of configmaps
  control-plane/config/post-install/200-controller-cluster-role.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
Labels: approved

#283 [release-v1.2] Support legacy KafkaChannel secret format
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/security/secrets_provider_legacy_channel_secret.go
  test/e2e-common.sh
  test/kafka/kafka_setup.sh
Labels: approved, lgtm

#282 [release-v1.2] Disable Sarama metrics since they are not exposed (#2225)
  control-plane/pkg/reconciler/kafka/client.go
  go.mod
  vendor/modules.txt
Labels: approved, lgtm
