Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2023-12, with the labels that each got.

#903 [release-v1.12] ignore unknown fields in data plane contract (#3486)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
Labels: approved, lgtm

#902 [release-v1.12] Remove activationLagThreshold to fix 0->1 scaling (#3479)
  control-plane/pkg/autoscaler/config.go
  control-plane/pkg/autoscaler/keda/keda.go
Labels: approved, lgtm

#910 Add patch to copy openshift-trusted-cabundle CM to namespaced broker namespace
  openshift/patches/namespaced_broker_copy_trustedca_cm.patch
Labels: approved

#911 [release-v1.11] Apply cm copy over 1.11
  control-plane/pkg/reconciler/broker/namespaced_broker.go
  openshift/patches/namespaced_broker_copy_trustedca_cm.patch
Labels: approved, lgtm

#904 [release-v1.11] ignore unknown fields in data plane contract (#3486)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
Labels: approved, lgtm

#920 Increase hardcoded PollTimeout value to 8m
  test/e2e_new/broker_test.go
Labels: approved, lgtm

#919 Update eventing nightly (#3530)
  ci
Labels: approved, kind/sync-fork-to-upstream

#923 [release-v1.11] Cherry-pick E2E tests for channel: TLS key pair rotation #3406
  control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml
  control-plane/pkg/prober/async_prober.go
  control-plane/pkg/prober/async_prober_test.go
  control-plane/pkg/prober/composite_prober.go
  control-plane/pkg/prober/composite_prober_test.go
  control-plane/pkg/prober/prober.go
  control-plane/pkg/prober/prober_test.go
  control-plane/pkg/prober/probertesting/mock_prober.go
  control-plane/pkg/prober/probertesting/mock_prober_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/channel/controller_test.go
  control-plane/pkg/reconciler/channel/resources/service.go
  control-plane/pkg/reconciler/channel/v2/channelv2.go
  control-plane/pkg/reconciler/channel/v2/channelv2_test.go
  control-plane/pkg/reconciler/channel/v2/controllerv2.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/testing/objects_channel.go
  test/e2e_new/channel_eventing_tls_test.go
  test/rekt/features/channel_tls.go
  test/rekt/resources/kafkachannel/kafkachannel.go
Labels: approved, lgtm

#929 Use ubi9 jdk 21 base images for dispatcher & receiver
  openshift/ci-operator/static-images/dispatcher/Dockerfile
  openshift/ci-operator/static-images/receiver/Dockerfile
Labels: approved, lgtm

#932 1.10 reconciler timeouts backport
  openshift/patches/reconciler-test-delete-resources-timeout-increase.patch
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
Labels: approved, lgtm

#934 [release-v1.9] tmp trigger build :robot:
  ci
Labels: approved

#925 [release-v1.11] Cherry-pick E2E tests for sink: TLS key pair rotation
  control-plane/config/eventing-kafka-broker/100-sink/100-kafka-sink.yaml
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/controller_test.go
  data-plane/config/sink/500-receiver.yaml
  test/e2e_new/sink_eventing_tls_test.go
  test/rekt/features/sink_tls.go
  test/rekt/resources/kafkasink/kafkasink.go
Labels: approved, lgtm
