Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2023-10, with the labels that each got.

#839 [release-v1.11] Cherry-pick Modify the existing fileWatcher to make it more generic (#3325)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/SecretWatcher.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
Labels: approved, lgtm

#840 Remove MAXFILLUP scheduler policy patch
  openshift/patches/maxfillup_scheduler.patch
Labels: approved, lgtm

#838 [release-v1.11] Cherry-pick Update the updateServerConfig function
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
Labels: approved, lgtm

#846 [release-v1.11] Create `eventing-kafka-tls-networking.yaml` artifact
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-channel.yaml
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka-source.yaml
  openshift/release/artifacts/eventing-kafka-tls-networking.yaml
  openshift/release/artifacts/eventing-kafka.yaml
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm

#843 [release-v1.10] Align version override with the Quarkus team
  data-plane/pom.xml
Labels: approved, lgtm

#845 [release-v1.11] updating to latest Quarkus 3.2.x version
  data-plane/pom.xml
Labels: approved, lgtm

#844 [release-v1.11] Update snappy override to latest
  data-plane/pom.xml
Labels: approved, lgtm

#849 [release-v1.11] Add the kafka-xyz.knative-eventing.svc as hostname (#3306)
  data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml
  data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml
  data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml
  openshift/release/artifacts/eventing-kafka-tls-networking.yaml
Labels: approved, lgtm

#855 Enable new-trigger-filter feature flag
  openshift/knative-eventing.yaml
Labels: approved, lgtm

#854 [release-v1.11] Workaround for cert-manager update spec issue (#3390)
  data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml
  data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml
  data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml
  openshift/release/artifacts/eventing-kafka-tls-networking.yaml
Labels: approved, lgtm

#858 [release-v1.10] Update patch list
  openshift/release/generate-release.sh
Labels: approved, lgtm

#857 [release-v1.9] Update patch list
  openshift/release/generate-release.sh
Labels: approved, do-not-merge/hold

#859 [release-v1.11] Update patch list
  openshift/release/generate-release.sh
Labels: approved, lgtm

#865 [release-v1.11] Allow skipping make generate-release in e2e_new_tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#867 [release-v1.11] Improve getting the script directory
  openshift/e2e-common.sh
Labels: approved, lgtm, do-not-merge/hold

#871 [release-1.10] use release-1.31 branch for S-O
  openshift/e2e-common.sh
Labels: approved, lgtm

#877 [release-v1.11] Updating to latest Quarkus (3.2.7.Final)
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#879 [release-v1.11] Add metrics to monitor the ConsumerGroup replicas changes (#3386)
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
Labels: approved, lgtm

#881 [release-v1.11] HTTP/2 disable patch from upstream
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: approved, lgtm

#880 [release-v1.10] HTTP/2 disable patch from upstream
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: approved, lgtm

#882 [release-v1.9] HTTP/2 disable patch from upstream
  openshift/patches/011-http2-cve.patch
  openshift/release/generate-release.sh
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm

#884 [release-v1.11] Patch for chmod on codegen files
  openshift/patches/chmod-codegen.patch
  openshift/release/generate-release.sh
  vendor/knative.dev/hack/codegen-library.sh
Labels: approved, lgtm

#878 [release-v1.11] Update ConsumerGroup status on finalization for better error reporting (#3415)
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/testing/objects_consumergroup.go
Labels: approved, lgtm

#885 [release-v1.11] Run `make generate-release`
  openshift/ci-operator/source-image/Dockerfile
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka.yaml
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, lgtm
