Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2024-01, with the labels that each got.

#942 Do not print sensitive information to logs
  openshift/e2e-common.sh
Labels: approved, lgtm

#950 [release-v1.12] Patch for chmod on codegen files
  hack/update-codegen.sh
  openshift/e2e-common.sh
  openshift/patches/chmod-codegen.patch
  openshift/release/generate-release.sh
  vendor/knative.dev/hack/codegen-library.sh
Labels: approved

#938 [release-v1.11] Revert 'logger bump' backport from upstream/main and go to latest 1.2.x logback
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#941 TestBrokerWithConfig waits for Topic in Requirement phase
  test/rekt/features/broker_config.go
Labels: approved, lgtm

#960 [release-v1.11] skip TestBrokerWithConfig
  test/e2e_new/broker_config_test.go
Labels: approved, lgtm

#901 [release-v1.11] Remove activationLagThreshold to fix 0->1 scaling (#3479)
  control-plane/pkg/autoscaler/config.go
  control-plane/pkg/autoscaler/keda/keda.go
Labels: approved, lgtm

#965 [release-v1.11] Bump to Go v1.21
  go.mod
  go.sum
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/post-install/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/release/artifacts/eventing-kafka-broker.yaml
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka-sink.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved, lgtm

#966 [release-v1.12] Bump to Go v1.21
  go.mod
  go.sum
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/post-install/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved, lgtm

#931 [release-v1.11] Cert injection, rely on workload's subPath injection
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
Labels: approved, do-not-merge/hold

#969 [release-v1.10] Updating logback-core to latest 1.12.x
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#973 [release-v1.11] Add makefile target for kafka keda tests
  Makefile
  openshift/e2e-common.sh
Labels: approved, lgtm

#974 [release-v1.11] Rename config-kafka-features feature flags to be consistent with eventing core feature flag names (#3512)
  control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml
  control-plane/pkg/apis/config/features.go
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/post-install/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/ci-operator/source-image/Dockerfile
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved, lgtm

#975 [release-v1.11] Backport fix for random consumer group id access
  control-plane/pkg/kafka/testing/admin_mock.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm
