Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2024-09, with the labels that each got.

#1166 [release-1.14] Expose OIDC audience of KafkaSink in its status
  control-plane/pkg/contract/contract.pb.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  test/e2e_new/sink_auth_test.go
  test/rekt/resources/kafkasink/kafkasink.go
  test/rekt/resources/kafkatopic/topic.go
Labels: approved, lgtm

#1164 [release-v1.15] Fix e2e tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#1159 [release-v1.15] Remove finalizer when trigger is deleted (#4046)
  control-plane/pkg/reconciler/trigger/v2/triggerv2.go
  control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
Labels: approved, lgtm

#1163 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-kafka-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-post-install.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-webhook-kafka.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-kafka-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-post-install.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-webhook-kafka.yaml
  .konflux/applications/serverless-operator-release-next/serverless-operator-release-next.yaml
  .tekton/docker-build.yaml
  .tekton/knative-eventing-kafka-broker-dispatcher-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-dispatcher-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-event-display-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-event-display-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-heartbeats-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-heartbeats-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-kafka-controller-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-kafka-controller-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-migrate-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-migrate-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-post-install-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-post-install-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-receiver-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-receiver-release-next-push.yaml
  .tekton/knative-eventing-kafka-broker-webhook-kafka-release-next-pull-request.yaml
  .tekton/knative-eventing-kafka-broker-webhook-kafka-release-next-push.yaml
Labels: approved, lgtm

#1165 [release-v1.15] Run `make generate-release`
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/post-install/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
Labels: approved, lgtm

#1162 [release-v1.15] Expose OIDC audience of KafkaSink in its status
  control-plane/pkg/contract/contract.pb.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  test/e2e_new/sink_auth_test.go
  test/rekt/resources/kafkasink/kafkasink.go
  test/rekt/resources/kafkatopic/topic.go
Labels: approved

#1151 [release-v1.15] fix: prober cache returns StatusUnknown by default (#4017)
  control-plane/pkg/prober/async_prober.go
  control-plane/pkg/prober/cache.go
  control-plane/pkg/prober/cache_test.go
Labels: approved, lgtm

#1229 Remove OCP bundle patch
  openshift/patches/OCP_Bundle_injection_kafka_data_plane.patch
Labels: approved, lgtm

#1257 [release-v1.15] Remove e2e test dependency on injection informers
  control-plane/pkg/reconciler/trigger/v2/triggerv2.go
  test/rekt/features/broker_deleted_recreated.go
Labels: approved, lgtm

#1256 Set globalResync function for KafkaChannel reconciler
  control-plane/pkg/reconciler/channel/controller.go
Labels: approved, lgtm, do-not-merge/hold

#1161 [release-v1.15] Create configmap for starting dispatcher pods (#4051)
  control-plane/cmd/kafka-controller/main.go
  control-plane/pkg/apis/internals/kafka/eventing/data_plane.go
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/register.go
  control-plane/pkg/reconciler/consumergroup/controller.go
  control-plane/pkg/reconciler/consumergroup/controller_test.go
  control-plane/pkg/reconciler/consumergroup/evictor_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/modules.txt
Labels: approved

#1158 [release-v1.15] fix: correct clusterrole permissions (#4016)
  control-plane/config/post-install/200-controller-cluster-role.yaml
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/post-install/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved

#1260 [release-v1.15] Add expected labels to static images
  openshift/ci-operator/static-images/dispatcher/Dockerfile
  openshift/ci-operator/static-images/receiver/Dockerfile
Labels: approved, lgtm

#1263 [release-v1.14] fix downstream build go toolchain error
  go.mod
Labels: approved, lgtm

#1254 Run e2e tests in bash
  Makefile
Labels: approved, lgtm

#1252 [main] Fix e2e tests (#1164)
  openshift/e2e-common.sh
Labels: approved, lgtm

#1266 [release-v1.15] Use v2 specific label to avoid matching previous deployment-based dispatchers
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_channel.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/testing/objects_source.go
Labels: approved, lgtm

#1279 [release-v1.14] Allow enabling sarama logging and disabling client pool and Upgrade knative.dev/eventing to latest 1.14
  control-plane/cmd/kafka-controller/main.go
  control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
  control-plane/pkg/kafka/clientpool/clientpool.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/namespaced_controller.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/consumergroup/controller.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/namespaced_controller.go
  go.mod
  go.sum
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/kafka-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/post-install/Dockerfile
  openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
  openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
  openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
  openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/e2e-common.sh
  openshift/patches/trigger_tests_set_annotations_correctly_now.patch
  openshift/release/artifacts/eventing-kafka-controller.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
  openshift/release/artifacts/eventing-kafka.yaml
  openshift/release/generate-release.sh
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/containersource.go
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/state/helpers.go
  vendor/knative.dev/eventing/pkg/scheduler/state/state.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/modules.txt
Labels: approved, lgtm

#1284 [release-v1.15] Set the `name` value for metrics tags to the correct top-level resource
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/consumer/consumer.go
  control-plane/pkg/reconciler/testing/objects_consumergroup.go
  control-plane/pkg/reconciler/trigger/v2/triggerv2.go
  control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
Labels: approved, lgtm

#1278 [release-v1.15] Allow enabling sarama logging and disabling client pool and Upgrade knative.dev/eventing to latest 1.15
  control-plane/cmd/kafka-controller/main.go
  control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
  control-plane/pkg/kafka/clientpool/clientpool.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/namespaced_controller.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/consumergroup/controller.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/namespaced_controller.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/state/helpers.go
  vendor/knative.dev/eventing/pkg/scheduler/state/state.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/modules.txt
Labels: approved, lgtm

#1281 [release-v1.15] Report error for unsupported PKCS #1 format for the private key
  control-plane/pkg/security/secret.go
  control-plane/pkg/security/secret_test.go
  control-plane/pkg/security/testdata/pkcs1_user.key
Labels: approved, lgtm

#1140 [release-v1.15] feat: use namespaced indexers for eventtypes in receiver (#4031)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImpl.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeListerFactory.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImplTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressProducer.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/AuthenticationHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java
Labels: approved, do-not-merge/hold
