Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2025-03, with the labels that each got.

#1572 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1582 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1583 Use default builder image in dockerfile generator
  openshift/generate.sh
Labels: approved, lgtm

#1589 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1581 [release-v1.17] Update Konflux configurations
  .tekton/kn-ekb-dispatcher-117-pull-request.yaml
  .tekton/kn-ekb-dispatcher-117-push.yaml
  .tekton/kn-ekb-event-display-117-pull-request.yaml
  .tekton/kn-ekb-event-display-117-push.yaml
  .tekton/kn-ekb-heartbeats-117-pull-request.yaml
  .tekton/kn-ekb-heartbeats-117-push.yaml
  .tekton/kn-ekb-kafka-controller-117-pull-request.yaml
  .tekton/kn-ekb-kafka-controller-117-push.yaml
  .tekton/kn-ekb-migrate-117-pull-request.yaml
  .tekton/kn-ekb-migrate-117-push.yaml
  .tekton/kn-ekb-post-install-117-pull-request.yaml
  .tekton/kn-ekb-post-install-117-push.yaml
  .tekton/kn-ekb-receiver-117-pull-request.yaml
  .tekton/kn-ekb-receiver-117-push.yaml
  .tekton/kn-ekb-test-committed-offset-117-pull-request.yaml
  .tekton/kn-ekb-test-committed-offset-117-push.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-117-pull-request.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-117-push.yaml
  .tekton/kn-ekb-test-event-sender-117-pull-request.yaml
  .tekton/kn-ekb-test-event-sender-117-push.yaml
  .tekton/kn-ekb-test-eventshub-117-pull-request.yaml
  .tekton/kn-ekb-test-eventshub-117-push.yaml
  .tekton/kn-ekb-test-kafka-consumer-117-pull-request.yaml
  .tekton/kn-ekb-test-kafka-consumer-117-push.yaml
  .tekton/kn-ekb-test-logs-exporter-117-pull-request.yaml
  .tekton/kn-ekb-test-logs-exporter-117-push.yaml
  .tekton/kn-ekb-test-print-117-pull-request.yaml
  .tekton/kn-ekb-test-print-117-push.yaml
  .tekton/kn-ekb-test-recordevents-117-pull-request.yaml
  .tekton/kn-ekb-test-recordevents-117-push.yaml
  .tekton/kn-ekb-test-request-sender-117-pull-request.yaml
  .tekton/kn-ekb-test-request-sender-117-push.yaml
  .tekton/kn-ekb-test-watch-cm-117-pull-request.yaml
  .tekton/kn-ekb-test-watch-cm-117-push.yaml
  .tekton/kn-ekb-test-wathola-fetcher-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-fetcher-117-push.yaml
  .tekton/kn-ekb-test-wathola-forwarder-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-forwarder-117-push.yaml
  .tekton/kn-ekb-test-wathola-receiver-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-receiver-117-push.yaml
  .tekton/kn-ekb-test-wathola-sender-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-sender-117-push.yaml
  .tekton/kn-ekb-webhook-kafka-117-pull-request.yaml
  .tekton/kn-ekb-webhook-kafka-117-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#1594 [release-v1.15] Update Konflux configurations
  .tekton/kn-ekb-dispatcher-115-pull-request.yaml
  .tekton/kn-ekb-dispatcher-115-push.yaml
  .tekton/kn-ekb-event-display-115-pull-request.yaml
  .tekton/kn-ekb-event-display-115-push.yaml
  .tekton/kn-ekb-heartbeats-115-pull-request.yaml
  .tekton/kn-ekb-heartbeats-115-push.yaml
  .tekton/kn-ekb-kafka-controller-115-pull-request.yaml
  .tekton/kn-ekb-kafka-controller-115-push.yaml
  .tekton/kn-ekb-migrate-115-pull-request.yaml
  .tekton/kn-ekb-migrate-115-push.yaml
  .tekton/kn-ekb-post-install-115-pull-request.yaml
  .tekton/kn-ekb-post-install-115-push.yaml
  .tekton/kn-ekb-receiver-115-pull-request.yaml
  .tekton/kn-ekb-receiver-115-push.yaml
  .tekton/kn-ekb-test-committed-offset-115-pull-request.yaml
  .tekton/kn-ekb-test-committed-offset-115-push.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-115-pull-request.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-115-push.yaml
  .tekton/kn-ekb-test-event-sender-115-pull-request.yaml
  .tekton/kn-ekb-test-event-sender-115-push.yaml
  .tekton/kn-ekb-test-eventshub-115-pull-request.yaml
  .tekton/kn-ekb-test-eventshub-115-push.yaml
  .tekton/kn-ekb-test-kafka-consumer-115-pull-request.yaml
  .tekton/kn-ekb-test-kafka-consumer-115-push.yaml
  .tekton/kn-ekb-test-logs-exporter-115-pull-request.yaml
  .tekton/kn-ekb-test-logs-exporter-115-push.yaml
  .tekton/kn-ekb-test-print-115-pull-request.yaml
  .tekton/kn-ekb-test-print-115-push.yaml
  .tekton/kn-ekb-test-recordevents-115-pull-request.yaml
  .tekton/kn-ekb-test-recordevents-115-push.yaml
  .tekton/kn-ekb-test-request-sender-115-pull-request.yaml
  .tekton/kn-ekb-test-request-sender-115-push.yaml
  .tekton/kn-ekb-test-watch-cm-115-pull-request.yaml
  .tekton/kn-ekb-test-watch-cm-115-push.yaml
  .tekton/kn-ekb-test-wathola-fetcher-115-pull-request.yaml
  .tekton/kn-ekb-test-wathola-fetcher-115-push.yaml
  .tekton/kn-ekb-test-wathola-forwarder-115-pull-request.yaml
  .tekton/kn-ekb-test-wathola-forwarder-115-push.yaml
  .tekton/kn-ekb-test-wathola-receiver-115-pull-request.yaml
  .tekton/kn-ekb-test-wathola-receiver-115-push.yaml
  .tekton/kn-ekb-test-wathola-sender-115-pull-request.yaml
  .tekton/kn-ekb-test-wathola-sender-115-push.yaml
  .tekton/kn-ekb-webhook-kafka-115-pull-request.yaml
  .tekton/kn-ekb-webhook-kafka-115-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#1586 [release-v1.16] Update Konflux configurations
  .tekton/kn-ekb-dispatcher-116-pull-request.yaml
  .tekton/kn-ekb-dispatcher-116-push.yaml
  .tekton/kn-ekb-event-display-116-pull-request.yaml
  .tekton/kn-ekb-event-display-116-push.yaml
  .tekton/kn-ekb-heartbeats-116-pull-request.yaml
  .tekton/kn-ekb-heartbeats-116-push.yaml
  .tekton/kn-ekb-kafka-controller-116-pull-request.yaml
  .tekton/kn-ekb-kafka-controller-116-push.yaml
  .tekton/kn-ekb-migrate-116-pull-request.yaml
  .tekton/kn-ekb-migrate-116-push.yaml
  .tekton/kn-ekb-post-install-116-pull-request.yaml
  .tekton/kn-ekb-post-install-116-push.yaml
  .tekton/kn-ekb-receiver-116-pull-request.yaml
  .tekton/kn-ekb-receiver-116-push.yaml
  .tekton/kn-ekb-test-committed-offset-116-pull-request.yaml
  .tekton/kn-ekb-test-committed-offset-116-push.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-116-pull-request.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-116-push.yaml
  .tekton/kn-ekb-test-event-sender-116-pull-request.yaml
  .tekton/kn-ekb-test-event-sender-116-push.yaml
  .tekton/kn-ekb-test-eventshub-116-pull-request.yaml
  .tekton/kn-ekb-test-eventshub-116-push.yaml
  .tekton/kn-ekb-test-kafka-consumer-116-pull-request.yaml
  .tekton/kn-ekb-test-kafka-consumer-116-push.yaml
  .tekton/kn-ekb-test-logs-exporter-116-pull-request.yaml
  .tekton/kn-ekb-test-logs-exporter-116-push.yaml
  .tekton/kn-ekb-test-print-116-pull-request.yaml
  .tekton/kn-ekb-test-print-116-push.yaml
  .tekton/kn-ekb-test-recordevents-116-pull-request.yaml
  .tekton/kn-ekb-test-recordevents-116-push.yaml
  .tekton/kn-ekb-test-request-sender-116-pull-request.yaml
  .tekton/kn-ekb-test-request-sender-116-push.yaml
  .tekton/kn-ekb-test-watch-cm-116-pull-request.yaml
  .tekton/kn-ekb-test-watch-cm-116-push.yaml
  .tekton/kn-ekb-test-wathola-fetcher-116-pull-request.yaml
  .tekton/kn-ekb-test-wathola-fetcher-116-push.yaml
  .tekton/kn-ekb-test-wathola-forwarder-116-pull-request.yaml
  .tekton/kn-ekb-test-wathola-forwarder-116-push.yaml
  .tekton/kn-ekb-test-wathola-receiver-116-pull-request.yaml
  .tekton/kn-ekb-test-wathola-receiver-116-push.yaml
  .tekton/kn-ekb-test-wathola-sender-116-pull-request.yaml
  .tekton/kn-ekb-test-wathola-sender-116-push.yaml
  .tekton/kn-ekb-webhook-kafka-116-pull-request.yaml
  .tekton/kn-ekb-webhook-kafka-116-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#1601 Update Quarkus to 3.8.6.SP3-redhat-00002
  data-plane/pom.xml
Labels: approved, lgtm

#1615 [release-v1.15] Fix post install being stuck if the channels are not enabled
  control-plane/cmd/post-install/kafka_channel_deployment_deleter.go
  control-plane/cmd/post-install/kafka_namespaced_broker_deployment_deleter.go
  control-plane/cmd/post-install/main.go
Labels: approved, lgtm

#1622 Running mvn CLI to update the THIRD-PARTY.txt
  data-plane/THIRD-PARTY.txt
Labels: approved, lgtm

#1597 [release-v1.17] Update Konflux configurations
  .tekton/kn-ekb-dispatcher-117-pull-request.yaml
  .tekton/kn-ekb-dispatcher-117-push.yaml
  .tekton/kn-ekb-event-display-117-pull-request.yaml
  .tekton/kn-ekb-event-display-117-push.yaml
  .tekton/kn-ekb-heartbeats-117-pull-request.yaml
  .tekton/kn-ekb-heartbeats-117-push.yaml
  .tekton/kn-ekb-kafka-controller-117-pull-request.yaml
  .tekton/kn-ekb-kafka-controller-117-push.yaml
  .tekton/kn-ekb-migrate-117-pull-request.yaml
  .tekton/kn-ekb-migrate-117-push.yaml
  .tekton/kn-ekb-post-install-117-pull-request.yaml
  .tekton/kn-ekb-post-install-117-push.yaml
  .tekton/kn-ekb-receiver-117-pull-request.yaml
  .tekton/kn-ekb-receiver-117-push.yaml
  .tekton/kn-ekb-test-committed-offset-117-pull-request.yaml
  .tekton/kn-ekb-test-committed-offset-117-push.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-117-pull-request.yaml
  .tekton/kn-ekb-test-consumer-group-lag-provider-test-117-push.yaml
  .tekton/kn-ekb-test-event-sender-117-pull-request.yaml
  .tekton/kn-ekb-test-event-sender-117-push.yaml
  .tekton/kn-ekb-test-eventshub-117-pull-request.yaml
  .tekton/kn-ekb-test-eventshub-117-push.yaml
  .tekton/kn-ekb-test-kafka-consumer-117-pull-request.yaml
  .tekton/kn-ekb-test-kafka-consumer-117-push.yaml
  .tekton/kn-ekb-test-logs-exporter-117-pull-request.yaml
  .tekton/kn-ekb-test-logs-exporter-117-push.yaml
  .tekton/kn-ekb-test-print-117-pull-request.yaml
  .tekton/kn-ekb-test-print-117-push.yaml
  .tekton/kn-ekb-test-recordevents-117-pull-request.yaml
  .tekton/kn-ekb-test-recordevents-117-push.yaml
  .tekton/kn-ekb-test-request-sender-117-pull-request.yaml
  .tekton/kn-ekb-test-request-sender-117-push.yaml
  .tekton/kn-ekb-test-watch-cm-117-pull-request.yaml
  .tekton/kn-ekb-test-watch-cm-117-push.yaml
  .tekton/kn-ekb-test-wathola-fetcher-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-fetcher-117-push.yaml
  .tekton/kn-ekb-test-wathola-forwarder-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-forwarder-117-push.yaml
  .tekton/kn-ekb-test-wathola-receiver-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-receiver-117-push.yaml
  .tekton/kn-ekb-test-wathola-sender-117-pull-request.yaml
  .tekton/kn-ekb-test-wathola-sender-117-push.yaml
  .tekton/kn-ekb-webhook-kafka-117-pull-request.yaml
  .tekton/kn-ekb-webhook-kafka-117-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#1620 Alternative hermetic setup + Quarkus 3.15.z update
  data-plane/pom.xml
  openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile.deps
  openshift/ci-operator/static-images/receiver/hermetic/Dockerfile.deps
Labels: approved, lgtm, ok-to-test

#1627 Add note how to fetch Quarkus version
  README.md
Labels: approved, lgtm

#1630 We must run mvn clean install
  data-plane/THIRD-PARTY.txt
Labels: approved, lgtm
