Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2025-05, with the labels that each got.

#1784 [release-v1.16] SRVKE-1720: Setup and initialize HTTPS server correctly when TLS config gets updated
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
Labels: approved, lgtm

#1783 [release-v1.16] SRVKE-1705 Fix initializer ocp
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
Labels: approved, lgtm, ok-to-test

#1794 Propagate the CaCerts and Audience of the ConsumerGroups Subscribers and DLS in the Triggers status too (#4365)
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1782 [release-v1.16] Run keda obj deletion only if the feature was previously enabled, to avoid GET requests for KEDA resources against the API server on each reconcilation
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_group_lifecycle.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_group_types.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
Labels: approved, lgtm, ok-to-test

#1809 [release-v1.16] Patch knative kafka controller post install role rule attribute
  control-plane/config/post-install/200-controller-cluster-role.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved, lgtm, ok-to-test

#1811 [release-v1.17] Patch knative kafka controller post install role rule attribute
  control-plane/config/post-install/200-controller-cluster-role.yaml
  openshift/release/artifacts/eventing-kafka-post-install.yaml
  openshift/release/artifacts/eventing-kafka.yaml
Labels: approved, lgtm, ok-to-test

#1802 [release-v1.16] Fix KEDA scaling with SASL auth for brokers (#4253)
  control-plane/pkg/autoscaler/keda/keda.go
  control-plane/pkg/security/secrets_provider_legacy_channel_secret.go
  test/rekt/features/keda_scaling.go
Labels: approved, lgtm, ok-to-test

#1821 [release-v1.16] Enable new test for SASL keda
  test/e2e_new/broker_test.go
  test/e2e_new/kafka_source_test.go
  test/rekt/features/keda_scaling.go
Labels: approved, lgtm

#1826 Remove patch to remove tracing config
  openshift/patches/remove_checksum_generation_for_config_tracing.patch
Labels: approved, lgtm
