Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2025-01, with the labels that each got.

#1392 [release-v1.15] Upgrade dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/hack/e2e-debug.sh
  vendor/knative.dev/eventing/pkg/auth/token_verifier.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1alpha1/eventpolicy/eventpolicy.go
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/state/state.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
  vendor/modules.txt
Labels: approved

#1396 [release-v1.15] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved

#1398 [release-v1.15] backport upstream broker_deleted_recreated rewrite
  test/rekt/features/broker_deleted_recreated.go
  test/rekt/features/sequence_assertions.go
Labels: approved, lgtm

#1401 [release-v1.15] Discard invalid consumer records (#4128)
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChain.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutator.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChainTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutatorTest.java
Labels: approved, lgtm

#1402 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#1390 [release-v1.16] Add Konflux configurations
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .konflux/applications/serverless-operator-136/tests/override-snapshot-ec-test.yaml
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, needs-ok-to-test

#1397 [release-v1.16] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved

#1393 [release-v1.16] Upgrade dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/hack/e2e-debug.sh
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/state/state.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
  vendor/modules.txt
Labels: approved

#1395 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  openshift/ci-operator/build-image/Dockerfile
Labels: needs-ok-to-test

#1416 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/serverless-operator-136.yaml
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .konflux/applications/serverless-operator-136/tests/override-snapshot-ec-test.yaml
Labels: needs-ok-to-test

#1415 [release-v1.15] Update Konflux configurations
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
Labels: needs-ok-to-test

#1414 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test
