Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2025-08, with the labels that each got.

#1871 bump to latest Quarkus LTS product version
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#1894 Update community files (#4478)
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1886 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm

#1946 [main] Update OWNERS file
  OWNERS
Labels: approved, lgtm

#1963 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1967 [release-v1.17] Revert quarkus bumps
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm, ok-to-test
