Repository openshift-knative/eventing-kafka-broker, pull requests merged in 2025-02, with the labels that each got.

#1460 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#1482 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1483 [release-v1.17] Bump to quarkus 3.15
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseToKafkaTopicHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImplTest.java
  data-plane/pom.xml
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java
Labels: approved, lgtm

#1466 [release-v1.16] Bump to quarkus 3.15
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseToKafkaTopicHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImplTest.java
  data-plane/pom.xml
  data-plane/profiler/run.sh
  data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java
  data-plane/receiver-loom/src/test/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java
Labels: approved, lgtm, ok-to-test

#1486 [release-v1.17] Going to latest of Quarkus 3.15 series
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm

#1490 Run AuthZ tests as part of Encryption/Auth test suite too
  openshift/e2e-common.sh
Labels: approved, lgtm

#1462 [release-v1.16] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
  .tekton/docker-java-build.yaml
Labels: needs-ok-to-test

#1461 [release-v1.15] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
  .tekton/docker-java-build.yaml
Labels: needs-ok-to-test

#1464 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
  .tekton/docker-java-build.yaml
Labels: needs-ok-to-test

#1488 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1505 Remove .editorconfig copy in Dockerfile
  openshift/ci-operator/static-images/dispatcher/Dockerfile
  openshift/ci-operator/static-images/receiver/Dockerfile
Labels: approved, lgtm

#1504 [release-v1.15] Upgrade Eventing deps to latest 1.15
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/modules.txt
Labels: approved, lgtm

#1508 [release-v1.16] Upgrade Eventing deps to latest 1.16
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm

#1509 :dizzy: Bump latest Quarkus and relevant dependencies (#4259)
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1536 [release-v1.15] Update Konflux configurations
  renovate.json
Labels: approved, needs-ok-to-test

#1538 [release-v1.17] Update Konflux configurations
  renovate.json
Labels: needs-ok-to-test

#1537 [release-v1.16] Update Konflux configurations
  renovate.json
Labels: needs-ok-to-test

#1542 Run hack generate tool directly
  openshift/e2e-common.sh
  openshift/generate.sh
Labels: approved, lgtm

#1559 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1560 [main] Update dependabot configurations
  renovate.json
Labels: approved, lgtm, needs-ok-to-test

#1535 Upgrade Eventing deps to latest 1.17
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/modules.txt
Labels: approved, lgtm

#1355 [release-v1.16] Thread safeness (backport)
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/auth/OIDCDiscoveryConfigListener.java
Labels: approved, lgtm

#1562 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream
